### ISSUE TITLE
[FEATURE] Add a append table feature

### ISSUE THREAD

**Issue by ediukill** [okube-ai/laktory#163]
### Problem Statement

I wish i was able to append two tables together (vertical join). 

### Proposed Solution

Add a new model to laktory/models/sql to handle joining two tables. Handle different columns names also?

**Comment by osoucy** [comment]
@ediukill vertical joins (or [unions](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.union.html)) are now supported with PR #170. This new feature has been released in [v0.1.9 ](https://pypi.org/project/laktory/0.1.9/).

An example on how to use it is available [here](https://www.laktory.ai/concepts/tablebuilder/#unions)

Handling different column names is always possible in joins and / or unions. For example, if you have table `slv_stock_prices_googl` with column `symbol` and table `slv_stock_prices_aapl` with column `sym`, you could still define the union using the select statement on the second table to rename its columns.

```py
- name: slv_stock_prices
  builder:
    layer: SILVER
    table_source:
      name: slv_stock_prices_googl
    unions:
      - other:
          name: slv_stock_prices_aapl
          selects:
              sym: symbol
              open: open
              close: close
              ...
          
    drop_source_columns: False
```
