### ISSUE TITLE
[FEATURE] Specify default workspace folder other than .laktory 

### ISSUE THREAD

**Issue by goda** [okube-ai/laktory#263]
### Problem Statement

First - great library! I am trying it out and it's looking very promising.

I am trying to figure out if we can specify a different folder name to which all of the scripts/files will get deployed to other than `.laktory`? Is this currently not supported, and if so is it easy to add? I am willing to help with PR as well!

Thanks!

### Proposed Solution

Add a way of configuring `stack.yaml` file to specify the default folder path into which to deploy all of the scripts/files.

**Comment by osoucy** [comment]
@goda  welcome to Laktory!
 
Sorry about the late response, but I did not have issues notifications turned on!
 
There are a couple of options to achieve your desired outcome and there is also room for improvment. Please refer to https://www.laktory.ai/api/models/resources/databricks/notebook/ for documentation of the attributes mentioned below.
 
1. Almost (hopefully all) files deployed to databricks workspace can have a full workspace path specified through the `path` attribute. This path must include the target directory and filename (including extension) of the file you want to upload. It completely ignores the path/filename of your the file on your local disk.
2. You can use `dirpath` to specify only the desired directory. Local filename will be re-used.
 
For reference, here is the current implementation:
```py
    @property
    def filename(self) -> str:
        """Notebook file name"""
        return os.path.basename(self.source)
 
    @model_validator(mode="after")
    def default_path(self) -> Any:
        if self.path is None:
            if self.dirpath:
                self.path = f"{self.dirpath}{self.filename}"
 
            elif "/notebooks/" in self.source:
                self.path = (
                    constants.LAKTORY_WORKSPACE_ROOT
                    + self.source.split("/notebooks/")[-1]
                )
 
        return self
```
 
You should also be able to configure env variable `LAKTORY_WORKSPACE_ROOT` to set the root directory of any file uploaded to the workspace when the `path` or `dirpath` attributes described above are not specified. Unfortuantely, it seems it has not been fully implemented yet and would require a few simple updates.
 
That being said, that environmnet variable would be "global" and not stack specific, as opposed to your proposed solution. Let me know if any of the existing solutions work for you, or if you feel that:
- configuration through LAKTORY_WORKSPACE_ROOT should be available
- configuration through a stack configuration is also necessary

**Comment by goda** [comment]
Hi @osoucy,

Thanks for that detailed explanation. I did stumble upon `LAKTORY_WORKSPACE_ROOT` by looking at the source code and tested it - and like you mentioned it works for some files but not all.

I am still new to using your library and noticed that if we do specify the `path` than the workspace location will be as expected.

In terms of the proposed solutions:
- using `LAKTORY_WORKSPACE_ROOT` can be helpful to do a catch all and make sure any files are all uploaded in that one workspace folder. It's easy enough to set the env variable during deployment so I am good with using this approach when needed
- If stack configuration would accomplish the same as the above solution, then depends on how much work is involved and whether that justifies the change?

To give you an idea of my motivation for all this - I currently have a Databricks workspace (dev) with jobs, notebooks and pipelines. I want to easily take those files and specify a folder for laktory to upload over into the workspace (e.g., `/.code/jobs`). If I have many notebooks/files I would love to be able to specify just the parent folder and have it copy them automatically without worrying about each file's path individually.

**Comment by osoucy** [comment]
This update should address most of your requests:
https://github.com/okube-ai/laktory/pull/272

The WorkspaceFile, DBFSFile and Notebook models are now consistent with each other and behave as follows:
- As before, the `path` attribute can be use to define the full path of a file
- If not defined, the path will be equals to `rootpath` / `dirpath` / {source_filename}. The `rootpath` can be specified as an argument, but can also be changed by setting `LAKTORY_WORKSPACE_LAKTORY_ROOT` env variable.

Also note that Laktory let you define variables. If you have a common dirpath for all your notebooks, you could use that in combination with the rootpath.

Let me know if that makes sense!

**Comment by osoucy** [comment]
Closed with https://github.com/okube-ai/laktory/pull/272
