### ISSUE TITLE
[FEATURE] Allow description field to be specified for jobs

### ISSUE THREAD

**Issue by goda** [okube-ai/laktory#277]
### Problem Statement

Currently laktory doesn't allow for specifying of `description` attribute for jobs, which is supported as per Databricks API - https://docs.databricks.com/api/workspace/jobs/create.

### Proposed Solution

In the `Job` class add the following attribute:
```
    description: str = None
```

**Comment by osoucy** [comment]
Closed in https://github.com/okube-ai/laktory/pull/278
